# Generated by Django 4.1.5 on 2023-02-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('dateofbirth', models.DateField(max_length=25)),
                ('gender', models.BooleanField()),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
    ]
