# Generated by Django 4.1.5 on 2023-02-25 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ketoconnect', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_details',
            new_name='User_detail',
        ),
    ]
