# Generated by Django 4.1.5 on 2023-02-25 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ketoconnect', '0002_rename_user_details_user_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Detail',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('placement_date', models.DateField(max_length=25)),
                ('delivery_date', models.DateField(max_length=25)),
                ('item_name', models.CharField(max_length=25)),
                ('total_items', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ketoconnect.user_detail')),
            ],
        ),
    ]
