# Generated by Django 4.1.5 on 2023-02-25 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ketoconnect', '0003_order_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal_Planner',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ketoconnect.user_detail')),
                ('target_calories', models.IntegerField()),
                ('food_choice_preferences', models.CharField(max_length=15)),
                ('intermittent_fasting', models.BooleanField()),
                ('recipe_preferences', models.CharField(max_length=15)),
                ('food_allergies', models.CharField(max_length=20)),
            ],
        ),
    ]
