# Generated by Django 4.1.5 on 2023-02-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ketoconnect', '0005_keto_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Food_category', models.CharField(max_length=15)),
                ('Food_Brand', models.CharField(max_length=15)),
            ],
        ),
    ]
