# Generated by Django 4.1.5 on 2023-02-25 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ketoconnect', '0006_food_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='KetoCalculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_Fat', models.FloatField()),
                ('total_net_carbs_per_day', models.IntegerField()),
                ('protein_consumed_each_day', models.IntegerField()),
                ('choose_a_goal', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.IntegerField()),
                ('street', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ketoconnect.order_detail')),
            ],
        ),
    ]
